volumes:
  node_modules:
  yarn_cache:
services:
  api:
    image: node:19-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    command: yarn dev -p 4157
    ports:
      - 4157:4157
